"use server";

export async function getTasksByUserIdActions(userId: string) {
  // const result = await prisma.task.findMany({
  //   where: {
  //     userId,
  //   },
  // });

  return [
    {
      id: "awad1-123",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-124",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: true,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-16",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: true,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-67",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-123",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-124",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: true,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-16",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: true,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-67",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-123",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-124",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: true,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-16",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: true,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
    {
      id: "awad1-67",
      title: "test title",
      description: "test description",
      date: "08/12/1999",
      isCompleted: false,
      isImportant: false,
      createdAt: "",
      updatedAt: "",
      userId: "awda",
    },
  ];
}
